package com.phu.ecommerceapi.reconciliation.application;

public enum ReconciliationIssueCode {
    UNBALANCED_LEDGER_TRANSACTION,
    MISSING_PAYMENT_LEDGER_TRANSACTION,
    PAYMENT_LEDGER_MISMATCH,
    MISSING_REFUND_LEDGER_TRANSACTION,
    REFUND_LEDGER_MISMATCH,
    ORPHANED_REFUND,
    ORPHANED_LEDGER_TRANSACTION
}
