package com.phu.ecommerceapi.reconciliation.application;

public enum ReconciliationIssueCode {
    UNBALANCED_LEDGER_TRANSACTION,
    MISSING_PAYMENT_LEDGER_TRANSACTION,
    PAYMENT_LEDGER_MISMATCH,
    MISSING_REFUND_LEDGER_TRANSACTION,
    REFUND_LEDGER_MISMATCH,
    ORPHANED_REFUND,
    ORPHANED_LEDGER_TRANSACTION,
    MISSING_PROVIDER_REFERENCE,
    PROVIDER_PAYMENT_STATE_MISMATCH,
    PROVIDER_REFUND_STATE_MISMATCH,
    ORPHANED_PROVIDER_WEBHOOK_EVENT,
    UNSUPPORTED_PAYMENT_PROVIDER
}
