spring.application.name=E-Commerce API
spring.profiles.default=local
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.mvc.problemdetails.enabled=true
management.endpoints.web.exposure.include=health,info,metrics

app.environment=${APP_ENVIRONMENT:local}
app.payment-provider=${PAYMENT_PROVIDER:fake}
app.authentication-provider=${AUTHENTICATION_PROVIDER:keycloak}
app.stripe.secret-key=${STRIPE_SECRET_KEY:}
app.fake-provider.webhook-secret=${FAKE_PROVIDER_WEBHOOK_SECRET:}
