spring.datasource.url=${ECOMMERCE_DB_URL:jdbc:postgresql://localhost:5433/ecommerce}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${ECOMMERCE_DB_USERNAME:ecommerce_app}
spring.datasource.password=${ECOMMERCE_DB_PASSWORD:ecommerce_app_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:demo-data.sql

app.environment=local
app.payment-provider=${PAYMENT_PROVIDER:fake}
app.authentication-provider=${AUTHENTICATION_PROVIDER:keycloak}
app.stripe.secret-key=${STRIPE_SECRET_KEY:}
app.fake-provider.webhook-secret=${FAKE_PROVIDER_WEBHOOK_SECRET:local-fake-webhook-secret}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${OAUTH2_JWK_SET_URI:http://localhost:8081/realms/ecommerce/protocol/openid-connect/certs}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH2_ISSUER_URI:http://localhost:8081/realms/ecommerce}
