spring.application.name=E-Commerce API
spring.profiles.default=local
spring.jpa.open-in-view=false
spring.flyway.enabled=true

app.environment=${APP_ENVIRONMENT:local}
app.payment-provider=${PAYMENT_PROVIDER:fake}
app.authentication-provider=${AUTHENTICATION_PROVIDER:legacy}
app.stripe.secret-key=${STRIPE_SECRET_KEY:}
