spring.datasource.url=${ECOMMERCE_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${ECOMMERCE_DB_USERNAME}
spring.datasource.password=${ECOMMERCE_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

app.environment=prod
app.payment-provider.active=${PAYMENT_PROVIDER_ACTIVE:}
app.payment-provider.enabled=${PAYMENT_PROVIDER_ENABLED:}
app.authentication-provider=${AUTHENTICATION_PROVIDER:keycloak}
app.fake-provider.webhook-secret=${FAKE_PROVIDER_WEBHOOK_SECRET:}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH2_ISSUER_URI}
