package com.phu.ecommerceapi.payment.api;

import com.phu.ecommerceapi.payment.application.ProviderWebhookResult;
import com.phu.ecommerceapi.payment.application.StripeProviderWebhookUseCase;
import com.phu.ecommerceapi.shared.api.OpenApiExamples;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/payments/provider-webhooks/stripe")
@Tag(
        name = "Provider Webhooks",
        description = "Payment provider callback endpoints. These are provider-to-API callbacks, not customer APIs."
)
public class StripeProviderWebhookController {

    public static final String STRIPE_SIGNATURE_HEADER = "Stripe-Signature";

    private final StripeProviderWebhookUseCase stripeProviderWebhookUseCase;

    public StripeProviderWebhookController(StripeProviderWebhookUseCase stripeProviderWebhookUseCase) {
        this.stripeProviderWebhookUseCase = stripeProviderWebhookUseCase;
    }

    @PostMapping
    @Operation(
            summary = "Handle Stripe provider webhook",
            description = "Receives raw Stripe webhook payloads, verifies the Stripe-Signature header, "
                    + "stores provider event ids idempotently, and applies payment/refund outcomes only "
                    + "after provider state checks."
    )
    @io.swagger.v3.oas.annotations.parameters.RequestBody(
            required = true,
            content = @Content(
                    mediaType = MediaType.APPLICATION_JSON_VALUE,
                    schema = @Schema(type = "object"),
                    examples = @ExampleObject(value = OpenApiExamples.STRIPE_WEBHOOK_REQUEST)
            )
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Webhook processed, ignored, or duplicate replay handled.",
                    content = @Content(
                            mediaType = MediaType.APPLICATION_JSON_VALUE,
                            schema = @Schema(implementation = ProviderWebhookResponse.class),
                            examples = @ExampleObject(value = OpenApiExamples.PROVIDER_WEBHOOK_RESPONSE)
                    )
            ),
            @ApiResponse(
                    responseCode = "202",
                    description = "Webhook accepted but rejected or marked for reconciliation.",
                    content = @Content(
                            mediaType = MediaType.APPLICATION_JSON_VALUE,
                            schema = @Schema(implementation = ProviderWebhookResponse.class),
                            examples = @ExampleObject(value = OpenApiExamples.PROVIDER_WEBHOOK_RESPONSE)
                    )
            ),
            @ApiResponse(
                    responseCode = "403",
                    description = "Missing or invalid Stripe webhook signature.",
                    content = @Content(
                            mediaType = MediaType.APPLICATION_JSON_VALUE,
                            schema = @Schema(implementation = ProviderWebhookResponse.class),
                            examples = @ExampleObject(value = OpenApiExamples.PROVIDER_WEBHOOK_REJECTED_RESPONSE)
                    )
            ),
            @ApiResponse(
                    responseCode = "409",
                    description = "Provider event id was reused with a different payload.",
                    content = @Content(
                            mediaType = MediaType.APPLICATION_JSON_VALUE,
                            schema = @Schema(implementation = ProviderWebhookResponse.class),
                            examples = @ExampleObject(value = OpenApiExamples.PROVIDER_WEBHOOK_REJECTED_RESPONSE)
                    )
            )
    })
    public ResponseEntity<ProviderWebhookResponse> handleWebhook(
            @Parameter(
                    description = "Stripe webhook signature header generated by Stripe for the raw request body.",
                    required = true
            )
            @RequestHeader(name = STRIPE_SIGNATURE_HEADER, required = false) String signatureHeader,
            @RequestBody(required = false) String requestBody
    ) {
        ProviderWebhookResult result = stripeProviderWebhookUseCase.handle(signatureHeader, requestBody);
        return ResponseEntity
                .status(result.httpStatus())
                .body(ProviderWebhookResponse.from(result.response()));
    }
}
