CREATE SEQUENCE cart_model_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE user_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    password VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255),
    address VARCHAR(255)
);

CREATE TABLE product_model (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    price DOUBLE PRECISION NOT NULL,
    stock DOUBLE PRECISION NOT NULL
);

CREATE TABLE cart_model (
    id BIGINT PRIMARY KEY,
    total DOUBLE PRECISION NOT NULL,
    owner_id BIGINT,
    CONSTRAINT fk_cart_model_owner
        FOREIGN KEY (owner_id) REFERENCES user_model (id)
);

CREATE TABLE cart_item_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity INTEGER NOT NULL,
    cart_id BIGINT,
    product_id BIGINT,
    CONSTRAINT fk_cart_item_model_cart
        FOREIGN KEY (cart_id) REFERENCES cart_model (id),
    CONSTRAINT fk_cart_item_model_product
        FOREIGN KEY (product_id) REFERENCES product_model (product_id)
);

CREATE INDEX idx_cart_model_owner_id ON cart_model (owner_id);
CREATE INDEX idx_cart_item_model_cart_id ON cart_item_model (cart_id);
CREATE INDEX idx_cart_item_model_product_id ON cart_item_model (product_id);
