CREATE TABLE reconciliation_run (
    id UUID PRIMARY KEY,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(20) NOT NULL,
    healthy BOOLEAN,
    payment_count BIGINT NOT NULL DEFAULT 0,
    refund_count BIGINT NOT NULL DEFAULT 0,
    ledger_transaction_count BIGINT NOT NULL DEFAULT 0,
    issue_count BIGINT NOT NULL DEFAULT 0,
    failure_message VARCHAR(1000),
    CONSTRAINT chk_reconciliation_run_status
        CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED')),
    CONSTRAINT chk_reconciliation_run_completed_status
        CHECK (status = 'RUNNING' OR completed_at IS NOT NULL)
);

CREATE INDEX idx_reconciliation_run_status_completed_at
    ON reconciliation_run (status, completed_at DESC);

CREATE TABLE reconciliation_issue_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id UUID NOT NULL,
    code VARCHAR(80) NOT NULL,
    resource_type VARCHAR(100) NOT NULL,
    resource_id VARCHAR(255),
    message VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_reconciliation_issue_run
        FOREIGN KEY (run_id) REFERENCES reconciliation_run (id) ON DELETE CASCADE
);

CREATE INDEX idx_reconciliation_issue_record_run_id_id
    ON reconciliation_issue_record (run_id, id);
