CREATE TABLE customer_order (
    id UUID PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    cart_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_customer_order_customer
        FOREIGN KEY (customer_id) REFERENCES user_model (id),
    CONSTRAINT fk_customer_order_cart
        FOREIGN KEY (cart_id) REFERENCES cart_model (id),
    CONSTRAINT chk_customer_order_status
        CHECK (status IN ('PENDING_PAYMENT', 'PAID', 'PAYMENT_FAILED', 'CANCELLED', 'REFUNDED')),
    CONSTRAINT chk_customer_order_total_non_negative
        CHECK (total_amount >= 0)
);

CREATE UNIQUE INDEX ux_customer_order_cart_id
    ON customer_order (cart_id);

CREATE INDEX idx_customer_order_customer_id
    ON customer_order (customer_id);

CREATE INDEX idx_customer_order_status_created_at
    ON customer_order (status, created_at);

CREATE TABLE customer_order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price_amount NUMERIC(19, 2) NOT NULL,
    line_total_amount NUMERIC(19, 2) NOT NULL,
    CONSTRAINT fk_customer_order_item_order
        FOREIGN KEY (order_id) REFERENCES customer_order (id),
    CONSTRAINT fk_customer_order_item_product
        FOREIGN KEY (product_id) REFERENCES product_model (product_id),
    CONSTRAINT chk_customer_order_item_quantity_positive
        CHECK (quantity > 0),
    CONSTRAINT chk_customer_order_item_unit_price_non_negative
        CHECK (unit_price_amount >= 0),
    CONSTRAINT chk_customer_order_item_line_total_non_negative
        CHECK (line_total_amount >= 0)
);

CREATE UNIQUE INDEX ux_customer_order_item_order_product
    ON customer_order_item (order_id, product_id);

CREATE INDEX idx_customer_order_item_product_id
    ON customer_order_item (product_id);
