CREATE TABLE payment_idempotency_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    endpoint VARCHAR(255) NOT NULL,
    operation VARCHAR(255) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    response_status INTEGER,
    response_body TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_payment_idempotency_customer
        FOREIGN KEY (customer_id) REFERENCES user_model (id),
    CONSTRAINT chk_payment_idempotency_status
        CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT chk_payment_idempotency_response_status
        CHECK (response_status IS NULL OR response_status BETWEEN 100 AND 599),
    CONSTRAINT chk_payment_idempotency_completed_fields
        CHECK (
            status <> 'COMPLETED'
            OR (
                response_status IS NOT NULL
                AND response_body IS NOT NULL
                AND completed_at IS NOT NULL
            )
        )
);

CREATE UNIQUE INDEX ux_payment_idempotency_scope
    ON payment_idempotency_record (customer_id, endpoint, operation, idempotency_key);

CREATE INDEX idx_payment_idempotency_customer_created_at
    ON payment_idempotency_record (customer_id, created_at);
