CREATE TABLE ledger_account (
    id UUID PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(30) NOT NULL,
    CONSTRAINT ux_ledger_account_code UNIQUE (code),
    CONSTRAINT chk_ledger_account_type
        CHECK (type IN ('ASSET', 'LIABILITY', 'REVENUE', 'EXPENSE', 'EQUITY'))
);

CREATE TABLE ledger_transaction (
    id UUID PRIMARY KEY,
    transaction_type VARCHAR(40) NOT NULL,
    reference_type VARCHAR(100) NOT NULL,
    reference_id VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    posted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_ledger_transaction_type
        CHECK (transaction_type IN ('PAYMENT_CAPTURE', 'REFUND'))
);

CREATE UNIQUE INDEX ux_ledger_transaction_reference
    ON ledger_transaction (reference_type, reference_id, transaction_type);

CREATE INDEX idx_ledger_transaction_posted_at
    ON ledger_transaction (posted_at);

CREATE TABLE ledger_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id UUID NOT NULL,
    account_id UUID NOT NULL,
    direction VARCHAR(10) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    CONSTRAINT fk_ledger_entry_transaction
        FOREIGN KEY (transaction_id) REFERENCES ledger_transaction (id),
    CONSTRAINT fk_ledger_entry_account
        FOREIGN KEY (account_id) REFERENCES ledger_account (id),
    CONSTRAINT chk_ledger_entry_direction
        CHECK (direction IN ('DEBIT', 'CREDIT')),
    CONSTRAINT chk_ledger_entry_amount_positive
        CHECK (amount > 0)
);

CREATE INDEX idx_ledger_entry_transaction_id
    ON ledger_entry (transaction_id);

CREATE INDEX idx_ledger_entry_account_currency
    ON ledger_entry (account_id, currency);

INSERT INTO ledger_account (id, code, name, type)
VALUES
    ('00000000-0000-0000-0000-000000000101', 'PAYMENT_PROVIDER_CLEARING', 'Payment provider clearing', 'ASSET'),
    ('00000000-0000-0000-0000-000000000102', 'ORDER_REVENUE', 'Order revenue', 'REVENUE');

CREATE OR REPLACE FUNCTION reject_ledger_mutation()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'ledger records are append-only';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_ledger_transaction_no_update
    BEFORE UPDATE OR DELETE ON ledger_transaction
    FOR EACH ROW EXECUTE FUNCTION reject_ledger_mutation();

CREATE TRIGGER trg_ledger_entry_no_update
    BEFORE UPDATE OR DELETE ON ledger_entry
    FOR EACH ROW EXECUTE FUNCTION reject_ledger_mutation();
